num_steps: 30000000
batch_size: 64
lr: 0.0003
memory_size: 1000000
gamma: 0.99
multi_step: 1
target_entropy_ratio: 0.98
start_steps: 1000
update_interval: 50
target_update_interval: 1000
use_per: False
#dueling_net: False
num_eval_steps: 1000000
max_episode_steps: 100000
log_interval: 10
eval_interval: 10000

